CREATE DATABASE IF NOT EXISTS evedeals;

CREATE USER 'ed'@'localhost' IDENTIFIED BY 'Katapushi2-';

GRANT ALL PRIVILEGES ON evedeals.* TO 'ed'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS solar_system (
    id     INT UNSIGNED NOT NULL DEFAULT 0 PRIMARY KEY,
    con_id INT UNSIGNED NOT NULL DEFAULT 0,
    name   VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS constellation (
    id     INT UNSIGNED NOT NULL DEFAULT 0 PRIMARY KEY,
    reg_id INT UNSIGNED NOT NULL DEFAULT 0,
    name   VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS region (
    id   INT UNSIGNED NOT NULL DEFAULT 0 PRIMARY KEY,
    name VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS types (
    id        INT UNSIGNED NOT NULL DEFAULT 0 PRIMARY KEY,
    pub       TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
    group_id  INT UNSIGNED NOT NULL DEFAULT 0,
    mgroup_id INT UNSIGNED NOT NULL DEFAULT 0,
    bprice    DECIMAL(16,2) UNSIGNED NOT NULL DEFAULT 0,
    volume    DECIMAL(24,4) UNSIGNED NOT NULL DEFAULT 0,
    name      VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS orders (
    id        BIGINT UNSIGNED NOT NULL DEFAULT 0 PRIMARY KEY,
    is_buy    TINYINT UNSIGNED NOT NULL DEFAULT 0,
    issued    DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
    duration  INT UNSIGNED NOT NULL DEFAULT 0,
    reg_id    INT UNSIGNED NOT NULL DEFAULT 0,
    loc_id    BIGINT UNSIGNED NOT NULL DEFAULT 0,
    sys_id    INT UNSIGNED NOT NULL DEFAULT 0,
    type_id   INT UNSIGNED NOT NULL DEFAULT 0,
    price     DECIMAL(32,2) UNSIGNED NOT NULL DEFAULT 0,
    vol_rem   INT UNSIGNED NOT NULL DEFAULT 0,
    min_vol   INT UNSIGNED NOT NULL DEFAULT 0
 );

